### ISSUE TITLE
float32 error, perhaps from ipywidgets

### ISSUE THREAD

**Issue by shimwell** [bernhard-42/cad-viewer-widget#3]
Hi @bernhard-42 

Thanks for making all these nice packages.

I just wanted to mention a bug that I'm seeing over here. This might be due to ipywidgets but just wanted to mention this in case the template being passed into ```embed_minimal_html``` is the cause of the ```TypeError: Object of type float32 is not JSON serializable``` bug

```
100% ⋮————————————————————————————————————————————————————————————⋮ (6/6)  0.02s
CadViewerWidget(anchor=None, cad_width=800, glass=False, height=600, pinning=False, theme='light', title=None, tools=True, tree_width=250)
<IPython.core.display.HTML object>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jshimwell/paramak/paramak/reactor.py", line 733, in export_html_3d
    view.export_html(filename)
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/site-packages/cad_viewer_widget/widget.py", line 1512, in export_html
    embed_minimal_html(filename, title=title, views=[self.widget], state=dependency_state(self.widget))
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/site-packages/ipywidgets/embed.py", line 302, in embed_minimal_html
    snippet = embed_snippet(views, **kwargs)
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/site-packages/ipywidgets/embed.py", line 279, in embed_snippet
    'json_data': escape_script(json.dumps(data['manager_state'], indent=indent)),
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 3 more times]
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/jshimwell/miniconda3/envs/openmc_dev_2/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable
```

**Comment by bernhard-42** [comment]
Hi @shimwell 
it is actually a bug in Jupyter Cadquery. I changed the behaviour of the algorithm and added a top level bounding box - which contains numpy values breaking `json.dump`

I have opened https://github.com/bernhard-42/jupyter-cadquery/issues/84, where you can also find a quick fix.
I am planning to release a new version this weekend, maybe that's sufficient for you

I will close this issue and track it with the issue in Jupyter Cadquery

**Comment by shimwell** [comment]
Thanks very much for looking into this. Awesome to to see fix on the other issue and hear about the release. Thanks so much

**Comment by bernhard-42** [comment]
@shimwell 
I saw you are using PartGroups. If you would use CadQuery Assemblies, the "explode" feature would work:
![reactor](https://user-images.githubusercontent.com/954408/184075985-7b1123ff-6d51-4bb6-8d0b-9b1ba8e139b7.gif)

**Comment by shimwell** [comment]
oh wow, I didn't know about that feature. I shall certainly get that added in. Thanks for showing the example and letting me know.
